# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LQ 2021
email: LQ2021Chairs@isti.cnr.it
description: > # this means to ignore newlines until "baseurl:"
  Learning to Quantify: Methods and Applications (LQ 2021)
description2: Colocated with the </br> <a class="nocolorlink" href="https://www.cikm2021.org/">30th ACM International Conference on Information and Knowledge Management</a> (CIKM 2021)</br>Gold Coast, Australia (an entirely online event)
description3: First International Workshop on
url: cikmlq2021.github.io
baseurl: ""
twitter_username: 
github_username:  pglez82

include: ["_pages"]

# Build settings
markdown: kramdown

